# Generated by Django 4.2.11 on 2024-05-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpayapp', '0002_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='not', max_length=100),
        ),
    ]
