# Generated by Django 3.2.12 on 2024-04-12 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0002_auto_20240412_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('extrafacility', models.TextField()),
                ('rental_choice', models.CharField(blank=True, choices=[('per month', 'Month'), ('per week', 'Week'), ('per day', 'Day')], max_length=20)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=10)),
                ('home_type', models.CharField(choices=[('rowhouse', 'Rowhouse'), ('colonial', 'Colonial'), ('flat', 'Flat'), ('cottage', 'Cottage'), ('bungalow', 'Bungalow'), ('other', 'Other')], default='rowhouse', max_length=10)),
                ('image1', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(upload_to='images')),
                ('image3', models.ImageField(upload_to='images')),
                ('image4', models.ImageField(upload_to='images')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
