# Generated by Django 3.2.12 on 2024-04-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20240412_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
