# Generated by Django 3.2.12 on 2024-04-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_listing_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
