# Generated by Django 3.2.12 on 2024-04-25 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0006_auto_20240422_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('which_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bookings', to='app2.listing')),
                ('booking_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
