# Generated by Django 3.2.12 on 2024-04-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_by',
            new_name='seller_listing',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_by',
            field=models.CharField(default=True, max_length=15),
        ),
    ]
