# Generated by Django 3.2.12 on 2024-04-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_auto_20240426_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.CharField(default=0, max_length=55),
        ),
    ]
