# Generated by Django 3.2.12 on 2024-04-27 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0010_remove_booking_seller_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
