# Generated by Django 4.2.11 on 2024-05-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_listing_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='statusmanage',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
